name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create config file
        run: |
          echo "{ \"replacementPatterns\": [ { \"pattern\": \"^/\", \"replacement\": \"${GITHUB_WORKSPACE}/\" } ] }" > config.json
          cat config.json
      - name: Find files
        run: |
          find "$(pwd -P)" -name '*.md' -not -path './node_modules/*'
          find "$(pwd -P)" -name '*.jpg' -not -path './node_modules/*'
          ls -la /home/runner/work/docs/docs/assets/images/fig_structs.jpg
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.3
        with:
          config-file: config.json
