name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create config file
        run: |
          echo "{ 'replacementPatterns': [ { 'pattern': '^/', 'replacement': $GITHUB_WORKSPACE } ] }"
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.3
          - config-file: config.json
